apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
