# please refer to https://external-secrets.io/latest/api/clustersecretstore/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: tsj-test
spec:
  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    # (1): AWS Secrets Manager
    # aws configures this store to sync secrets using AWS Secret Manager provider
    aws:
      service: SecretsManager
      # Role is a Role ARN which the SecretManager provider will assume
      role: arn:aws:iam::xxx:role/esorole
      # AWS Region to be used for the provider
      region: us-west-2
      # Auth defines the information necessary to authenticate against AWS
      auth:
        # Getting the accessKeyID and secretAccessKey from an already created Kubernetes Secret
        # secretRef:
        #   accessKeyIDSecretRef:
        #     name: awssm-secret
        #     key: access-key
        #   secretAccessKeySecretRef:
        #     name: awssm-secret
        #     key: secret-access-key
        # IAM roles for service accounts
        # https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
        jwt:
          serviceAccountRef:
            name: esosa
            namespace: external-secrets
