apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: myapp
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: tsj-test
    kind: ClusterSecretStore
  target:
    name: tsj-test-secret
    creationPolicy: Owner
  data:
  - secretKey: tsj-test-username
    remoteRef:
      key: dev/test/username
      property: username
  - secretKey: tsj-test-another-username
    remoteRef:
      key: dev/test/username
      property: anotherusername
  dataFrom:
  - extract:
      key: dev/test/keys
