apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app: myapp
    app.kubernetes.io/component: api
  name: tsj-test-secret-provider
  namespace: myapp
spec:
  parameters:
    objects: |
      - objectName: "dev/test/sandbox"
        objectType: "secretsmanager"
        jmesPath:
        - path: key1
          objectAlias: 'key1'
        - path: key2
          objectAlias: 'key2'
  provider: aws
  secretObjects:
  - data:
    - key: key1
      objectName: key1
    - key: key2
      objectName: key2
    secretName: tsj-test-secret-2024-12-26
    type: Opaque
