apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
spec:
  containers:
  - name: nginx
    image: dhutsj/nginx:v3
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "4Gi"
      requests:
        memory: "2Gi"
