apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-nginx
  namespace: argocd
spec:
  generators:
  # This is a list generator, reference here https://argocd-applicationset.readthedocs.io/en/stable/Generators-List/
  - list:
      elements:
      - cluster: minikube
        url: https://kubernetes.default.svc
#     - cluster: staging
#       url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-my-nginx'
      namespace: default
    spec:
      project: default
      source:
        repoURL: https://github.com/dhutsj/k8s-practice.git
        targetRevision: HEAD
        path: nginx-kustomize-demo/overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated: {}
        syncOptions: 
          - CreateNamespace=true